/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BackIcon: typeof import('./src/components/Icons/BackIcon.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    ExitIcon: typeof import('./src/components/Icons/ExitIcon.vue')['default']
    FavoriteIcon: typeof import('./src/components/Icons/FavoriteIcon.vue')['default']
    FeedbackIndex: typeof import('./src/components/Feedback/FeedbackIndex.vue')['default']
    GoogleIcon: typeof import('./src/components/Icons/GoogleIcon.vue')['default']
    HomeIcon: typeof import('./src/components/Icons/HomeIcon.vue')['default']
    LayoutIndex: typeof import('./src/components/Layout/LayoutIndex.vue')['default']
    LikeIcon: typeof import('./src/components/Icons/LikeIcon.vue')['default']
    LoginIndex: typeof import('./src/components/Login/LoginIndex.vue')['default']
    LogoIcon: typeof import('./src/components/Icons/LogoIcon.vue')['default']
    MusicCard: typeof import('./src/components/Card/MusicCard.vue')['default']
    MusicIcon: typeof import('./src/components/Icons/MusicIcon.vue')['default']
    PlayIcon: typeof import('./src/components/Icons/PlayIcon.vue')['default']
    PlayMusicIcon: typeof import('./src/components/Icons/PlayMusicIcon.vue')['default']
    ProfileIcon: typeof import('./src/components/Icons/ProfileIcon.vue')['default']
    ResetIndex: typeof import('./src/components/Reset/ResetIndex.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectIcon: typeof import('./src/components/Icons/SelectIcon.vue')['default']
    SignUpIndex: typeof import('./src/components/SignUp/SignUpIndex.vue')['default']
    VideoCard: typeof import('./src/components/Card/VideoCard.vue')['default']
    VideoIcon: typeof import('./src/components/Icons/VideoIcon.vue')['default']
  }
}
